MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 4 #number of classes, need to be checked
  FASTER_RCNN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /home/amax/workspace/detectron-models/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('security_train_auto_synthesis',  'security_train_pro_synthesis',  'security_train_real_package')
  SCALES: (800,)
  MAX_SIZE: 1333
# using 600x800 to be consistent with Rong and Zhengxin
#  SCALES: (600,)
#  MAX_SIZE: 800
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
###### optional ####
# forground faction, default is 0.25, maybe lower would make false rate lower
#  FG_FRACTION: 0.1
# difficulty of background, default is [0.0 - 0.5], may be 0.1 - 0.5? not too difficult
#  BG_THRESH_HI: 0.5
#  BG_THRESH_LO: 0.1  
  RPN_FG_FRACTION: 0.2
TEST:
  DATASETS: ('security_val_hlx', 'security_val_mzl', 'security_val_dongle_synthesis', 'security_test_zhongyunzhihui', 'security_test_mzl_kongbao', 'security_test_travel_packages')
  SCALE: 800
  MAX_SIZE: 1333
#  SCALE: 600
#  MAX_SIZE: 800
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
OUTPUT_DIR: .
